version: "3.8"
services:
  web:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    env_file:
      - /home/developer/.env.dev

  postgres:
    image: postgres:13.3
#    volumes:
#      - postgres_volume:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "gemstones"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
