# Generated by Django 4.1.5 on 2023-02-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
