# Generated by Django 4.1.5 on 2023-02-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemstones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
